### ISSUE TITLE
Error checking pattern unclear

### ISSUE THREAD

**Issue by nate-anderson** [rqlite/gorqlite#45]
In this simple example:

```go
var db *gorqlite.Connection

func storeUser(email string) error {
        var userName string
        wr, err := db.WriteOneParameterized(gorqlite.ParameterizedStatement{
	        Query:     "INSERT INTO users (email) VALUES (?)",
	        Arguments: []any{email},
        })
        if err != nil {
                return err
        }
        if wr.Err != nil {
                return wr.Err
        }
        return nil
}
```

It is unclear what purpose the second return value of `WriteOneParameterized` serves. If one of the statements errors, its value is an error string stating "there were 1 statement errors" - I find this unhelpful because now I have to inspect the write result error property to know what the error actually was. I'm checking two errors to understand one failure.

Is there any case where `WriteOneParameterized` will _not_ return an error, but a write result will contain an error? Why not simply return the detailed error contained in the write result when there is only one write statement? Even when calling `WriteParameterized`, in my opinion, it makes more sense to expose the detailed error(s) in the idiomatic Go way, rather than expecting the caller to check multiple errors until they find their desired level of detail. `errors.Join` is a very easy way to condense multiple errors into a single value, such as when multiple statements encounter errors. If, for some reason, it's important to keep statement errors distinct from each other, why return an error from `WriteOneParameterized` at all, instead of requiring the caller to check each WriteResult's error explicitly?

**Comment by otoolep** [comment]
This has got to do with the nature of the rqlite API. The API can fail in two ways:

- a HTTP errors code, e.g. 404. Perhaps your client hits entirely the wrong server, not even an rqlite server. You might get back 404 in that case.
- an application-level error, such as bad SQL. That is indicated by the `error` key in the response.

I consider the rqlite API itself correct, but I agree there is a case to be made the Go client should internally check for both and just set `err` as you suggest - and if either indicates an error return that err. For backwards-compatibility reasons we would leave `wr.Err` in place and set, but the docs would say to ignore it.

WDYT?

**Comment by nate-anderson** [comment]
I think that's reasonable - the `database/sql` package does something similar when querying a single row, the caller can check the error result either from the row struct itself, or the result of trying to call the `Scan` method - the important thing, IMO, is that the error message is specific in both places, and that a nil error is not returned for a failed API call.

**Comment by a-h** [comment]
I have raised PR #47 which enables unwrapping etc., and includes detail in the top level error message.

**Comment by a-h** [comment]
You used to need to do this:

```go
results, err := q.conn.WriteParameterizedContext(ctx, statements)
if err != nil {
	var errs []error
	for _, result := range results {
		errs = append(errs, result.Err)
	}
	return errors.Join(errs...)
}
```

Since https://github.com/rqlite/gorqlite/commit/45bc609b8c35a735529f4b0ac47283cbae5145fc errors will result in an error message that contains all required error information.

So the code can be simplified to:

```go
if _, err = q.conn.WriteParameterizedContext(ctx, statements); err != nil {
	return err
}
```

I this this issue should now be closed.

**Comment by otoolep** [comment]
Thanks.
